
package com.lntormin.javaee.ejb.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://services.ejb.javaee.lntormin.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "insertUser", targetNamespace = "http://services.ejb.javaee.lntormin.com/", className = "com.lntormin.javaee.ejb.services.InsertUser")
    @ResponseWrapper(localName = "insertUserResponse", targetNamespace = "http://services.ejb.javaee.lntormin.com/", className = "com.lntormin.javaee.ejb.services.InsertUserResponse")
    public void insertUser(
        @WebParam(name = "user", targetNamespace = "")
        User user);

    /**
     * 
     * @param id
     * @return
     *     returns com.lntormin.javaee.ejb.services.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://services.ejb.javaee.lntormin.com/", className = "com.lntormin.javaee.ejb.services.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://services.ejb.javaee.lntormin.com/", className = "com.lntormin.javaee.ejb.services.FindByIdResponse")
    public User findById(
        @WebParam(name = "id", targetNamespace = "")
        int id);

}
